# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
